### ISSUE TITLE
Dungeon: The Nexus: Weird LoS behavior of some mobs

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#20]
"Mage hunter ascedant" mobs keep casting on you (doing no damage, only animation) even tho you are behind a wall. 

**Screenshots:**

![wowscrnshot_041417_183615](https://cloud.githubusercontent.com/assets/27430839/25038442/6d92fac4-2131-11e7-9cec-f0a9ad31447a.jpg)

**Comment by Deathtremor** [comment]
I did another test. 

***** This problem seems to acured only for frost version of Mage Hunter Ascendant mob. The other two version: fire and arcane version seems to work properly.

I also found anothertwo issues with Arcane version of the very same mob.

* Missing ability/spell:: Polymorph
* They don't try to attack by melee attacks even tho go on melee range.

**Comment by JunkyBulgaria** [comment]
I've rewritten their AI now it should be much more advanced.
TODO: Frosbolt phase, need to code the frostbolt spell as it does not have script currently and it's completely broken. ref: http://prntscr.com/ewpth8

**Comment by Deathtremor** [comment]
The Cone of Cold AOE should definitely affect all enemies within 20y. (up up to 5 ) It should be same for all versions including 3.3.5.

**Comment by JunkyBulgaria** [comment]
Currently it is in 20y range, all issues in this thread has been fixed, you can test them.

**Comment by Deathtremor** [comment]
Ok i re-tested. 

* The LoS issue with frostball seems to be fixed.

Issues that still occurs.

* When you step on: Freezing Trap not always you get frozen. Sometimes when you step on the trap the trap just desepire without any effect on you.

* Arcane and Fire version of Mage Hunter Ascendant seems to be somehow mixed now. Fire version of the mob is using arcane spells as well. 

* Some of Mage Hunter Ascendants are standing in the air ( screenshot below)

![wowscrnshot_041517_202750](https://cloud.githubusercontent.com/assets/27430839/25063034/a6ad5a98-221c-11e7-873f-b35b484ca440.jpg)

**Comment by JunkyBulgaria** [comment]
About the new issues
1) Freezing Trap - sometimes misses due to low-level mobs.
2) Should be working as intended now, forgot to apply scriptnames.
3) That's their "Levitate" / "Hover" effect.

**Comment by Deathtremor** [comment]
* Sometimes animation for melee attacks is missing

* Arcane version of the mob still missing ability: Polymorph

* For some reason they kneel sometimes when you pull them and during fight.

* They wont attack you unless you go on melee range.You can stand 2 hours in from of them (out of their range) and they will not attack. ^^

**Comment by JunkyBulgaria** [comment]
1) i need to test it out
2) will investigate it
3) should be releated to 1)
4) that's due to level difference 

thanks
