### ISSUE TITLE
[Quest][Northrend][Icecrown] Assault by Air

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#301]
# Assault by Air

### How it is supposed to work:

The quest itself is perfectly completable. But the turrets you face while flying around Ymirheim should attack the plane.  In order to prevent them to shoot your plane, you have to use your ability (something like a smokegranate)

### Current Issue

The turrets in Ymirheim don't attack the plane

How to reproduce:

Get into the plane
Fly with it and observe the turrets

### Screenshots
![wowscrnshot_051417_162055](https://cloud.githubusercontent.com/assets/24325735/26034773/fc848598-38c1-11e7-8205-35b9b78cc8c6.jpg)

![wowscrnshot_051417_162059](https://cloud.githubusercontent.com/assets/24325735/26034776/007659ce-38c2-11e7-8349-02efe9659e1f.jpg)

![wowscrnshot_051417_162107](https://cloud.githubusercontent.com/assets/24325735/26034780/03bae1a4-38c2-11e7-8b14-ec3aebf22236.jpg)

### Video of the working quest

https://www.youtube.com/watch?v=oLA35CMTFCU

**Comment by frytik** [comment]
Should be fixed on next-restart.

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Not working, Turrets still not attacking or beeing able to destroyed by the ability.
