### ISSUE TITLE
[Naxxramas] Patchwork Trash

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#349]
The room in which patchwork is running around:

The hole trash aggros if you pull a group.
But if you pull Patchwork the trash won't aggro.

![wowscrnshot_052317_002127](https://cloud.githubusercontent.com/assets/24325735/26331124/9f1b6446-3f4f-11e7-9e70-1bd4d56d565c.jpg)

![wowscrnshot_052317_002126](https://cloud.githubusercontent.com/assets/24325735/26331126/a0798836-3f4f-11e7-93d4-7a40ceec3f33.jpg)

**Comment by JunkyBulgaria** [comment]
wasn't this fixed in open beta and marked as working? needs testing

**Comment by Demmye** [comment]
Confirmed, everything in this report is correct.

**Comment by philoudu16** [comment]
All the trash still gets pulled at once when you pull one (on PTR)

**Comment by JunkyBulgaria** [comment]
should be working now

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

Pulling a group of adds does **not** aggro all mobs in the area. This is fixed.
