### ISSUE TITLE
Dungeon: Halls Of Lightning (Normal): NPC: Slag

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#46]
**Description:**

NPC: Slag 
¨
Ability: **Melt Armor** is supposed to stacks.  Currently it won't. It reduce only 1000 armor no matter how many times they hit you.

Source: http://www.wowhead.com/guides/dungeons/timewalking/halls-of-lightning-strategy-guide

**Comment by frytik** [comment]
Confirmed. In fixing.

**Comment by frytik** [comment]
Fixed.

**Comment by Deathtremor** [comment]
**Re-tested and it still not working! Need to to re-opened!**

**Comment by Deathtremor** [comment]
Re-tested! Nothing has been fixed. Still the same issues! The escort is still broken. + The quest won't get complated after the escort quest ends.

**Comment by JunkyBulgaria** [comment]
@Deathtremor it is not applied yet, we are updating compiling tools.

**Comment by Deathtremor** [comment]
**Re-tested after the update.

Still doen't work both for heroic and normal!**

**Comment by frytik** [comment]
@Deathtremor Can you re-test ?
